### ISSUE TITLE
provide helper function for parent to detect grand children changes and retire event mechanism

### ISSUE THREAD

**Issue by bencao** [freewheel/modulajs#4]
## Description

Event mechanism is something feeling exotic in modulajs, and can make application going complicated very soon.

Today we already offer a different approach with modelDidUpdate lifecycle.
But we probably lacking some helper functions to make it more convenient so that we can retire event mechanism completely.

### Info

A proposal:

```
modelDidUpdate(oldModel, newModel) {
  ifChanged(oldModel, newModel, ['decoratedModel', 'messages'], (oldChild, newChild) => {
   // Do some stuff here to handle grand child change
  })
}
```

**Comment by hua-lu** [comment]
IMO, the idea behind event-system is decoupling, and neither data-sharing (through model context) nor modelDidUpdate can replace it.

**Comment by bencao** [comment]
close since it's implemented in the **next** branch.
