### ISSUE TITLE
support native list/object as first class citizen

### ISSUE THREAD

**Issue by bencao** [freewheel/modulajs#6]
## Description

Currently we enforced the check of immutable types which can be too strict.
Actually we can delegate the choice of immutability check to user land.

No matter users want to use immutablejs, or immerjs, or their own typescript/flow checker to ensure immutability, that can be their freedom.

### Info
In order to achieve this, we may need to:

- [ ] Add native list/object support to model.
- [ ] Make 'propTypes' optional.

**Comment by robinyy** [comment]
Agree with the proposal, but want to confirm that we don't want to remove the immutability of the Model but just not have a hard dependency on `immutable.js`

**Comment by bencao** [comment]
closed since it's implemented in the **next** branch.
